### ISSUE TITLE
Doubt

### ISSUE THREAD

**Issue by apdevzhang** [akiroom/AXRatingView#28]
why not publish to cocoapods

**Comment by apdevzhang** [comment]
sorry say that, I was hurry to comment when I didn't finish reading

**Comment by akiroom** [comment]
It seems to be broken now.

I can confirm AXRatingView has been still in Cocoapods Specs at here: https://github.com/CocoaPods/Specs/tree/d0ec5a65e80656c8d78e12ff19f251df879e0bc2/Specs/9/7/4/AXRatingView

But I tried to search "AXRatingView" and got nothing. https://cocoapods.org/?q=RatingView
[![https://gyazo.com/fe209d043589e5c95336dcd5189687e4](https://i.gyazo.com/fe209d043589e5c95336dcd5189687e4.png)](https://gyazo.com/fe209d043589e5c95336dcd5189687e4)

When I searched a common word, and it returns nothing also. So, I doubt that something went wrong in Cocoapods. https://cocoapods.org/?q=http
[![https://gyazo.com/eaa769a0b5073b8acc15fd4117dafb90](https://i.gyazo.com/eaa769a0b5073b8acc15fd4117dafb90.png)](https://gyazo.com/eaa769a0b5073b8acc15fd4117dafb90)

**Comment by apdevzhang** [comment]
I have download it from
 cocoapods aha


| |
张磊
邮箱：greenbanyan@163.com
|

签名由 网易邮箱大师 定制

On 04/27/2018 18:49, Hiroki Akiyama wrote:

Cocoapods seems to be broken now.

I can confirm AXRatingView has been still in Cocoapods Specs at here: https://github.com/CocoaPods/Specs/tree/d0ec5a65e80656c8d78e12ff19f251df879e0bc2/Specs/9/7/4/AXRatingView

But I tried to search "AXRatingView" and got nothing. https://cocoapods.org/?q=RatingView


When I searched a common word, and it returns nothing also. So, I doubt that something went wrong in Cocoapods. https://cocoapods.org/?q=http
